version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - printenv
      - aws sts get-caller-identity
      - export ACCOUNT_NUMBER=`aws sts get-caller-identity --query 'Account' --output text`
      - echo $ACCOUNT_NUMBER
      - echo $AWS_DEFAULT_REGION
      - echo $CODEBUILD_BUILD_NUMBER
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Build ID input to index file...
      - chmod +x updateIndex.sh 
      - ./updateIndex.sh
      - echo Building the Docker image...          
      - docker build -t demo/ecs .
      - docker tag demo/ecs:latest $ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CODEBUILD_BUILD_ID
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CODEBUILD_BUILD_ID
      - echo Writing image definitions file...
      - printf '[{"name":"demoEcs","imageUri":"%s"}]' $ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CODEBUILD_BUILD_ID > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
#    - '**/*'